### PR TITLE
Release v3.0.0

### PR DESCRIPTION
**Pull request by stephane-caron**
This major release adds *Control Barrier Functions* developed by @domrachev03 and @simeon-ned :+1: Examples of what we can do with barriers include:

- [Arm: UR5](https://github.com/stephane-caron/pink/tree/b9be1feb825b39ac56a795daef0695f86cc948ca/examples/barriers#arm-ur5): with joints and end effector limits
- [Humanoid: G1](https://github.com/stephane-caron/pink/blob/37591fedbfa66df9c972c3e0c88815185bda13b9/examples/humanoid_g1_com.py): G1 humanoid squatting via a CoM task
- [Quadruped: Go2](https://github.com/stephane-caron/pink/tree/b9be1feb825b39ac56a795daef0695f86cc948ca/examples/barriers#go2-squat): Go 2 squatting with floating base position limits
- [Dual Arms: Yumi](https://github.com/stephane-caron/pink/tree/b9be1feb825b39ac56a795daef0695f86cc948ca/examples/barriers#yumi-end-effector-self-collision-avoidance): self-collision avoidance with spheres
- [Dual Arms: Iiwa](https://github.com/stephane-caron/pink/tree/b9be1feb825b39ac56a795daef0695f86cc948ca/examples/barriers#iiwa-whole-body-collision-avoidance): whole-body self-collision avoidance

https://github.com/domrachev03/pink/assets/28687492/d64163b6-399f-4bbf-ac50-1135fa69c2da

Another API-breaking change to the library is that *limits* are now optional and can be extended (for instance with the new acceleration limit) or disabled. New limits and tasks include:

- Limit: `AccelerationLimit`
- Task: `ComTask` for center-of-mass tracking (thanks to @simeon-ned)
- Task: `LowAccelerationTask` for smoother velocities.

Check out the full changelog below for other changes and fixes. May the Motion be with you!

### Added

- **Breaking:** Updated the logic for handling the joint limits:
  - Add a ``limits`` argument to ``build_ik`` and ``solve_ik``
  - The `check_limits` method now includes an optional `safety_break` argument to control whether execution should stop on exception.
  - The ``solve_ik`` function now includes the `safety_break` that is forwarded to `check_limits`.
- Control Barrier Functions, namely: (thanks to @domrachev03 and @simeon-ned)
  - Abstract Barrier ``Barrier``
  - Frame Position Barrier ``PositionBarrier``
  - Body Spherical Barrier ``BodySphericalBarrier``
  - Whole-body Self-Collision Avoidance Barrier ``SelfCollisionBarrier``
- Example: UR5 manipulator and GO2 quadruped robot with `PositionBarrier`
- Example: YUMI two-armed manipulator with `BodySphericalBarrier`
- Example: G1 humanoid squatting through regulating CoM.
- Limit: `AccelerationLimit`
- Task: `ComTask` for center-of-mass tracking (thanks to @simeon-ned)
- Task: `LowAccelerationTask` for smoother velocities.

### Changed

- **Breaking:** remove ``lm_damping`` parameter from DampingTask where it wasn't used
- CICD: Update ruff to 0.4.3
- Configuration accepts list of Control Barrier Functions
- DampingTask: Simplify implementation
- Update to Pinocchio 3 with 2.7 backward compatibility

### Fixed

- PostureTask: Match implementation and documentation formula
- Fix broken documentation links

### Removed

- CICD: Disable macOS checks until upstream PyPI package is fixed

### CODE REVIEW

**Comment by stephane-caron** [comment]
@domrachev03 and @simeon-ned: I've drafted the release message for Pink 3.0.0 in the PR description above :point_up_2: Don't hesitate to make suggestions. Once it sounds good to you, let's hit release and unroll the new version to conda-forge and PyPI :smiley:

**Comment by simeon-ned** [comment]
Hello @stephane-caron,

I'm glad to see the new release! It was indeed a great experience contributing to PINK. Everything looks great on my end, with just one suggestion: it would be beneficial to add a [hyperlink to the CoM example](https://github.com/stephane-caron/pink/blob/main/examples/humanoid_g1_com.py). Additionally, I might include the CoM task video in the [examples README](https://github.com/stephane-caron/pink/blob/main/examples/README.md).

Best regards

**Comment by domrachev03** [comment]
Hello @stephane-caron,

I am excited to see a new release too, and have no any extra suggestions on top of @simeon-ned ones. Waiting for the moment when self-collision barriers could be installed from PyPI :tada: 

Looking forward to continue working on other features/projects together!

**Comment by stephane-caron** [comment]
Thank you both for your feedback.

> it would be beneficial to add a [hyperlink to the CoM example](https://github.com/stephane-caron/pink/blob/main/examples/humanoid_g1_com.py).

Done :+1: 

> Additionally, I might include the CoM task video in the [examples README](https://github.com/stephane-caron/pink/blob/main/examples/README.md).

Sounds good. Feel free to do it in a quick PR, then I will rebase this PR on it and do the release.

**Pull request merged**
